[phases.setup]
aptPkgs = [
    "build-essential",  
    "python3-dev",      
    "libssl-dev",       
    "cargo",           
    "libmysqlclient-dev",
    "python3-pip"
]
pythonVersion = "3.11"

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  "/opt/venv/bin/pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
